FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 8080
ENV ASPNETCORE_URLS=http://+:8080

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["VentaMap.ChatService/VentaMap.ChatService.csproj", "VentaMap.ChatService/"]
RUN dotnet restore "VentaMap.ChatService/VentaMap.ChatService.csproj"
COPY . .
WORKDIR "/src/VentaMap.ChatService"
RUN dotnet publish "VentaMap.ChatService.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "VentaMap.ChatService.dll"]
